### ISSUE TITLE
segments of party member's hp and party member's pet's hp don't line up

### ISSUE THREAD

**Issue by fuzzlecutter** [NilliP/NillipussUI_1080p#1]
![image](https://github.com/user-attachments/assets/985c7dc8-57ad-4d67-908a-c8848b9a8c79)

**Comment by NilliP** [comment]
Thanks for report, fixed for next release.
You can grab the file [here](https://github.com/NilliP/NillipussUI_1080p/blob/main/NillipussUI_1080p/Options/Theme%20-%20Bars%20-%20Flat%20%26%20Segmented/Segemented%20Bars/dzbars.png) if you need it before release
