### ISSUE TITLE
Pet Sit/Stand button is broken

### ISSUE THREAD

**Issue by andrewejones88** [NilliP/NillipussUI_1080p#2]
Fresh install of Quarm, Zeal, and Nillipus 1080p. My pet sit/stand button looks like this and doesn't function at all:
![image](https://github.com/user-attachments/assets/5db96f83-4fdc-4eb9-88d3-bc73624ee2c8)

**Comment by andrewejones88** [comment]
I replaced the PetInfo file with the one from default, and it works as expected but obviously doesn't match.

**Comment by NilliP** [comment]
Should be fixed in latest release
